### ISSUE TITLE
AttributeError: module 'click' has no attribute 'get_terminal_size'

### ISSUE THREAD

**Issue by MaxwellEblock** [tokern/lakecli#26]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ops/bin/lakecli", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/ops/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/ops/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/ops/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/ops/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/ops/lib/python3.8/site-packages/lakecli/main.py", line 725, in cli
    athenacli.run_cli()
  File "/opt/anaconda3/envs/ops/lib/python3.8/site-packages/lakecli/main.py", line 291, in run_cli
    self.cli = self._build_cli(history)
  File "/opt/anaconda3/envs/ops/lib/python3.8/site-packages/lakecli/main.py", line 581, in _build_cli
    reserve_space_for_menu=self.get_reserved_space()
  File "/opt/anaconda3/envs/ops/lib/python3.8/site-packages/lakecli/main.py", line 630, in get_reserved_space
    _, height = click.get_terminal_size()
AttributeError: module 'click' has no attribute 'get_terminal_size'

**Comment by MaxwellEblock** [comment]
❯ cat app.log
2022-07-16 17:36:12,133 (46451/MainThread) lakecli.sqlexecute INFO - Connect to /Users/maxwellli/.lakecli/iamdb
2022-07-16 17:36:12,135 (46451/completion_refresh) lakecli.sqlexecute INFO - Connect to /Users/maxwellli/.lakecli/iamdb
2022-07-16 17:38:18,215 (46653/MainThread) lakecli.main INFO - Scanning Lake Formation Permissions
2022-07-16 17:38:18,215 (46653/MainThread) lakecli.main INFO - Scanning Lake Formation Permissions
2022-07-16 17:38:18,215 (46653/MainThread) lakecli.iam.scanner INFO - Remove old sqlite database at /Users/maxwellli/.lakecli/iamdb
2022-07-16 17:38:18,816 (46653/MainThread) lakecli.iam.scanner INFO - 0 table permissions found.
2022-07-16 17:38:18,817 (46653/MainThread) lakecli.iam.scanner INFO - 0 database permissions found.
2022-07-16 17:38:19,336 (46653/MainThread) lakecli.iam.scanner INFO - 0 databases found
2022-07-16 17:38:19,365 (46653/MainThread) lakecli.sqlexecute INFO - Connect to /Users/maxwellli/.lakecli/iamdb
2022-07-16 17:38:19,367 (46653/completion_refresh) lakecli.sqlexecute INFO - Connect to /Users/maxwellli/.lakecli/iamdb
2022-07-16 17:40:32,215 (46907/MainThread) lakecli.sqlexecute INFO - Connect to /Users/maxwellli/.lakecli/iamdb
2022-07-16 17:40:32,218 (46907/completion_refresh) lakecli.sqlexecute INFO - Connect to /Users/maxwellli/.lakecli/iamdb

**Comment by gh-pankaj-saini** [comment]
This seems to fix the error:

https://github.com/nexB/scancode-toolkit/issues/2904#issuecomment-1084595072

**Comment by vrajat** [comment]
A fix similar to https://github.com/nexB/commoncode/commit/14a142d18ccff4746d20010cbb7a1db08d58cc94 is required.
